---
- name: Deploy app
  hosts: all
  connection: local
  become: true
  become_user: root
  vars:
    deployment_path: '/home/ubuntu/app'
    compose_path: './docker-compose.yml'
  roles:
    - geerlingguy.docker
  tasks:
  - name: Update apt
    ansible.builtin.apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600
  - name: Install pip
    ansible.builtin.package:
      name: python3-pip
      state: present
  - name: Install docker using pip
    ansible.builtin.pip:
      name:
        - requests==2.31.0
        - docker<7.0
        - docker-compose
  - name: Create directory
    ansible.builtin.file:
      path: "{{ deployment_path }}"
      state: directory
  - name: Copy docker compose to directory
    ansible.builtin.copy:
      src: "{{ compose_path }}"
      dest: "{{ deployment_path }}"
  - name: Run docker compose
    become: true
    community.docker.docker_compose:
      project_src: "{{ deployment_path }}"
      build: yes
      debug: yes
    environment:
      FRONTEND_IMAGE: "{{ lookup('env','FRONTEND_IMAGE') }}"
      BACKEND_IMAGE:  "{{ lookup('env','BACKEND_IMAGE') }}"
